services:
  db:
    container_name: kanban-db
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: kanban
      MYSQL_USER: kanban
      MYSQL_PASSWORD: bw1qJGj
    ports:
      - 3306:3306
    volumes:
      - kanban-mysql-data:/var/lib/mysql
    networks:
      - kanban-network

volumes:
  kanban-mysql-data:

networks:
  kanban-network:
    driver: bridge
