services:
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: kanban
      MYSQL_USER: kanban
      MYSQL_PASSWORD: bw1qJGj
    ports:
      - 6000:3306
    volumes:
      - kanban-mysql-data:/var/lib/mysql
    restart: always

volumes:
  kanban-mysql-data:
